### PR TITLE
Remove transpile for ES2015 on development - Fix #79

### LINKED ISSUE #79: Disable ES2015 transpile on development mode
**Current behavior**

At the moment we are compiling the JS every time even on development mode, at the moment Google Chrome has support for almost all the features of the new version of JS.

**Expected/desired behavior**

For development there is no really a reason to compile to the JS using babel we should do the complication as a process just before the deployment to staging or production, this will help to increase the speed of debugging and writing code during development.

### PR DESCRIPTION
**Pull request by mitogh**
- **What kind of change does this PR introduce?** (Bug fix, feature,
  docs update, ...)
- Fix #79
- **What is the current behavior?** (You can also link to an open issue
  here)

Explained on #79 
- **What is the new behavior (if this is a feature change)?**

Does not transpile ES2015 JS
- **Does this PR introduce a breaking change?** (What changes might
  users need to make in their application due to this PR?)

No
- **Other information**:

No

### CODE REVIEW

**Comment by adamf321** [comment]
@mitogh I assume ES 2016 is similarly implemented in Chrome and FF?

**Comment by mitogh** [comment]
I'm not sure what do you mean here, would you mind explaining a bit more?

Thanks.

**Comment by adamf321** [comment]
I'm checking that there won't be any issues for devs who use FF.

**Comment by mitogh** [comment]
At the moment, V8 has a 98% support of ES2016 and some support for ES7 as well. So shouldn't be a problem. And it's pretty well supported on firefox as well and other browsers. 

http://kangax.github.io/compat-table/es6/

**Pull request merged**
